window.RB = window.RB || {};
RB.STR = {
  app:{en:"RingBeat",ar:"نبض الحلبة"},
  tag:{en:"Gym-like boxing, Muay Thai & kickboxing",ar:"تدريب كصالة حقيقية للملاكمة والمواي تاي والكيك بوكسينغ"},
  home:{en:"Home",ar:"الرئيسية"}, train:{en:"Train",ar:"تدريب"}, timer:{en:"Timer",ar:"مؤقّت"},
  builder:{en:"Combos",ar:"الكومبو"}, stats:{en:"Stats",ar:"إحصائيات"},
  start:{en:"Start",ar:"ابدأ"}, resume:{en:"Resume",ar:"استكمال"}, pause:{en:"Pause",ar:"إيقاف"},
  skip:{en:"Skip",ar:"تخطي"}, rest:{en:"Rest",ar:"راحة"}, round:{en:"Round",ar:"الجولة"},
  combo:{en:"Combo",ar:"كومبو"}, done:{en:"Session complete",ar:"انتهت الحصة"},
  again:{en:"Train again",ar:"تدريب آخر"}, homeCta:{en:"Back home",ar:"العودة"},
  bag:{en:"Punching bag",ar:"كيس اللكم"}, shadow:{en:"Shadowboxing",ar:"ملاكمة ظل"},
  boxing:{en:"Boxing",ar:"ملاكمة"}, muaythai:{en:"Muay Thai",ar:"مواي تاي"}, kickboxing:{en:"Kickboxing",ar:"كيك بوكسينغ"},
  beginner:{en:"Beginner",ar:"مبتدئ"}, intermediate:{en:"Intermediate",ar:"متوسط"}, advanced:{en:"Advanced",ar:"متقدم"},
  chooseStyle:{en:"Choose your style",ar:"اختر أسلوبك"}, featured:{en:"Workouts",ar:"الحصص"},
  quickTimer:{en:"Ad-free round timer",ar:"مؤقّت جولات بلا إعلانات"},
  customizable:{en:"Customizable workouts",ar:"حصص قابلة للتخصيص"},
  diverse:{en:"Bag or shadow — diverse training",ar:"كيس أو ظل — تدريب متنوع"},
  gymLike:{en:"Gym-like workouts",ar:"حصص كالصالة"},
  streak:{en:"Day streak",ar:"سلسلة الأيام"}, sessions:{en:"Sessions",ar:"حصص"}, minutes:{en:"Minutes",ar:"دقائق"},
  saveCombo:{en:"Save combo",ar:"حفظ الكومبو"}, emptyCombo:{en:"Build a sequence, then save it.",ar:"ركّب سلسلة ثم احفظها."},
  rounds:{en:"Rounds",ar:"جولات"}, roundLen:{en:"Round time",ar:"مدة الجولة"}, restLen:{en:"Rest time",ar:"مدة الراحة"},
  reviews:{en:"What fighters say",ar:"ماذا يقول المقاتلون"}, nextMove:{en:"Up next",ar:"التالي"},
  hunt:{en:"Hunt hard. Recover fully.",ar:"اصطد بقوة. استرد بالكامل."},
  startWorkout:{en:"Start workout",ar:"ابدأ الحصة"},
  prepare:{en:"Set your stance. Eyes on the bag.",ar:"ثبّت وقفتك. العين على الكيس."},
  shadowHint:{en:"Open floor. Mirror the sequence.",ar:"مساحة مفتوحة. طابق السلسلة."},
  editCombos:{en:"Edit combinations",ar:"تعديل التركيبات"},
  saved:{en:"Saved locally on this device.",ar:"محفوظ على هذا الجهاز."},
  noWorkouts:{en:"No workouts in this filter.",ar:"لا حصص ضمن هذا الفلتر."},
  delete:{en:"Delete",ar:"حذف"}, clearCombo:{en:"Clear",ar:"مسح"}, myCombos:{en:"Your combinations",ar:"تركيباتك"},
  bestAward:{en:"Best boxing PWA 2026",ar:"أفضل تطبيق ملاكمة 2026"},
  thisWeek:{en:"This week",ar:"هذا الأسبوع"}, lastSession:{en:"Last session",ar:"آخر حصة"},
  noneYet:{en:"No sessions yet — start a round.",ar:"لا حصص بعد — ابدأ جولة."},
  language:{en:"Language",ar:"اللغة"}, theme:{en:"Appearance",ar:"المظهر"},
  fights:{en:"Fights",ar:"نزالات"}, more:{en:"More",ar:"المزيد"},
  install:{en:"Install app",ar:"ثبّت التطبيق"},
  installHint:{en:"Add RingBeat to your Home Screen — works offline.",ar:"أضف نبض الحلبة لشاشتك الرئيسية — يعمل بلا إنترنت."},
  installIos:{en:"On iPhone: tap Share, then Add to Home Screen.",ar:"على آيفون: اضغط مشاركة ثم «إضافة إلى الشاشة الرئيسية»."},
  installAndroid:{en:"Tap Install, then confirm Add to Home Screen.",ar:"اضغط تثبيت ثم أكّد الإضافة للشاشة الرئيسية."},
  installed:{en:"Opening as installed app",ar:"يعمل كتطبيق مثبّت"},
  later:{en:"Later",ar:"لاحقاً"},
  share:{en:"Share",ar:"مشاركة"},
  shareProgress:{en:"Share progress",ar:"مشاركة التقدّم"},
  shareWorkout:{en:"Share workout",ar:"مشاركة التمرين"},
  a11y:{en:"Accessibility",ar:"إمكانية الوصول"},
  contrast:{en:"High contrast",ar:"تباين عالٍ"},
  largeType:{en:"Larger text",ar:"خط أكبر"},
  reduceMotion:{en:"Reduce motion",ar:"تقليل الحركة"},
  captions:{en:"Captions",ar:"ترجمة نصية"},
  haptic:{en:"Haptics",ar:"اهتزاز"},
  voiceCue:{en:"Voice cues",ar:"إرشاد صوتي"},
  bell:{en:"Round bell",ar:"جرس الجولة"},
  importLive:{en:"Refresh cards",ar:"تحديث البطاقات"},
  sources:{en:"Sources",ar:"المصادر"},
  upcoming:{en:"Upcoming cards",ar:"البطاقات القادمة"},
  mma:{en:"MMA / UFC",ar:"فنون قتالية / UFC"},
  allFights:{en:"All",ar:"الكل"},
  getTickets:{en:"Open card",ar:"افتح البطاقة"},
  theFight:{en:"The Fight",ar:"النزال"},
  workRate:{en:"Work rate punch/min",ar:"معدل اللكمات / دقيقة"},
  punches:{en:"Punches",ar:"لكمات"},
  elapsed:{en:"Elapsed",ar:"المستغرق"},
  power:{en:"Power",ar:"القوة"},
  speed:{en:"Speed",ar:"السرعة"},
  plan:{en:"Week plan",ar:"خطة الأسبوع"},
  liveImport:{en:"Imported from fight trackers",ar:"مستورد من مواقع تتبّع النزالات"},
  copied:{en:"Copied — send it to a friend.",ar:"تم النسخ — أرسله لصديق."},
  close:{en:"Close",ar:"إغلاق"},
  skipTo:{en:"Skip to training",ar:"تخطَّ إلى التدريب"},
  rankings:{en:"UFC men's P4P",ar:"تصنيف الرجال P4P"},
  rankingsW:{en:"UFC women's P4P",ar:"تصنيف النساء P4P"},
  quotes:{en:"From the cage",ar:"من القفص"}
};
RB.t = (lang, key) => (RB.STR[key] && RB.STR[key][lang]) || key;
RB.MOVES = [
  {id:"jab",en:"Jab",ar:"جاب",styles:["boxing","muaythai","kickboxing"]},
  {id:"cross",en:"Cross",ar:"كروس",styles:["boxing","muaythai","kickboxing"]},
  {id:"lead-hook",en:"Lead hook",ar:"هوك أمامي",styles:["boxing","muaythai","kickboxing"]},
  {id:"rear-hook",en:"Rear hook",ar:"هوك خلفي",styles:["boxing","muaythai","kickboxing"]},
  {id:"lead-upper",en:"Lead uppercut",ar:"أبركت أمامي",styles:["boxing","muaythai","kickboxing"]},
  {id:"rear-upper",en:"Rear uppercut",ar:"أبركت خلفي",styles:["boxing","muaythai","kickboxing"]},
  {id:"body-jab",en:"Body jab",ar:"جاب للجسم",styles:["boxing","muaythai","kickboxing"]},
  {id:"body-cross",en:"Body cross",ar:"كروس للجسم",styles:["boxing","muaythai","kickboxing"]},
  {id:"body-hook",en:"Body hook",ar:"هوك للجسم",styles:["boxing","muaythai","kickboxing"]},
  {id:"slip-l",en:"Slip left",ar:"انزلاق يسار",styles:["boxing","muaythai","kickboxing"]},
  {id:"slip-r",en:"Slip right",ar:"انزلاق يمين",styles:["boxing","muaythai","kickboxing"]},
  {id:"roll",en:"Roll",ar:"رول",styles:["boxing"]},
  {id:"guard",en:"High guard",ar:"حراسة عالية",styles:["boxing","muaythai","kickboxing"]},
  {id:"lead-kick",en:"Lead kick",ar:"ركلة أمامية",styles:["muaythai","kickboxing"]},
  {id:"rear-mid-kick",en:"Rear mid kick",ar:"ركلة وسطى خلفية",styles:["muaythai","kickboxing"]},
  {id:"roundhouse",en:"Roundhouse",ar:"ركلة دائرية",styles:["muaythai","kickboxing"]},
  {id:"switch-kick",en:"Switch kick",ar:"ركلة تبديل",styles:["muaythai","kickboxing"]},
  {id:"teep",en:"Teep",ar:"تيب",styles:["muaythai"]},
  {id:"low-kick",en:"Low kick",ar:"ركلة منخفضة",styles:["muaythai","kickboxing"]},
  {id:"knee",en:"Knee",ar:"ركبة",styles:["muaythai"]},
  {id:"elbow",en:"Elbow",ar:"كوع",styles:["muaythai"]},
  {id:"pushups",en:"Push-ups",ar:"ضغط",styles:["boxing","muaythai","kickboxing"]}
];
RB.MOVE_MAP = Object.fromEntries(RB.MOVES.map(m => [m.id, m]));
const C = (id, moves, holdSec=8) => ({id, moves, holdSec});
RB.WORKOUTS = [
  {id:"jab-lab",en:"Jab laboratory",ar:"مختبر الجاب",blurbEn:"Clean lead hand. Sightline. Snap back to guard.",blurbAr:"يد أمامية نظيفة. خط نظر. عُد للحراسة فوراً.",style:"boxing",mode:"bag",level:"beginner",rounds:3,roundSec:120,restSec:45,combos:[C("c1",["jab","jab","guard"],7),C("c2",["jab","cross"],6),C("c3",["jab","jab","cross"],8),C("c4",["body-jab","jab","cross"],8)]},
  {id:"shadow-flow",en:"Shadow flow",ar:"تدفق الظل",blurbEn:"Footwork and defense without the bag.",blurbAr:"خطوات ودفاع بلا كيس.",style:"boxing",mode:"shadow",level:"beginner",rounds:4,roundSec:180,restSec:60,combos:[C("c1",["jab","slip-l","cross"],8),C("c2",["jab","cross","slip-r","lead-hook"],10),C("c3",["roll","rear-hook","guard"],8)]},
  {id:"power-bag",en:"Power bag",ar:"كيس القوة",blurbEn:"Hip torque. Rear hand through the bag.",blurbAr:"عزم الورك. اليد الخلفية تخترق الكيس.",style:"boxing",mode:"bag",level:"intermediate",rounds:5,roundSec:180,restSec:60,combos:[C("c1",["jab","cross","lead-hook"],8),C("c2",["cross","lead-hook","rear-hook"],8),C("c3",["jab","body-cross","rear-upper"],9)]},
  {id:"twelve-round",en:"Twelve-round fight",ar:"نزال اثنتي عشرة جولة",blurbEn:"Championship cadence.",blurbAr:"إيقاع بطولة.",style:"boxing",mode:"bag",level:"advanced",rounds:12,roundSec:180,restSec:60,combos:[C("c1",["jab","jab","cross"],7),C("c2",["jab","cross","lead-hook"],8),C("c3",["slip-r","lead-hook","cross"],8)]},
  {id:"muay-rhythm",en:"Muay rhythm",ar:"إيقاع المواي",blurbEn:"Teep to measure. Rear mid kick to break rhythm.",blurbAr:"تيب للقياس. ركلة وسطى خلفية لكسر الإيقاع.",style:"muaythai",mode:"bag",level:"intermediate",rounds:5,roundSec:180,restSec:60,combos:[C("c1",["jab","cross","teep"],8),C("c2",["jab","rear-mid-kick"],7),C("c3",["elbow","knee","rear-mid-kick"],9)]},
  {id:"clinch-mix",en:"Knees & elbows",ar:"ركب ومرافق",blurbEn:"Close range. Compact weapons.",blurbAr:"مسافة قريبة. أسلحة مضغوطة.",style:"muaythai",mode:"shadow",level:"advanced",rounds:4,roundSec:150,restSec:50,combos:[C("c1",["jab","elbow","knee"],8),C("c2",["teep","switch-kick"],7)]},
  {id:"kick-cut",en:"Kick cut",ar:"قطع الركل",blurbEn:"Low then high. Hands set the kick.",blurbAr:"منخفضة ثم عالية. اليدان تمهّدان الركلة.",style:"kickboxing",mode:"bag",level:"intermediate",rounds:6,roundSec:120,restSec:40,combos:[C("c1",["jab","cross","low-kick"],8),C("c2",["jab","rear-mid-kick"],7),C("c3",["cross","lead-hook","roundhouse"],9)]},
  {id:"core-mix",en:"Bag & body",ar:"كيس وجسم",blurbEn:"Strikes then push-ups.",blurbAr:"ضربات ثم ضغط.",style:"boxing",mode:"bag",level:"beginner",rounds:4,roundSec:90,restSec:40,combos:[C("c1",["jab","cross","jab","cross"],10),C("c2",["pushups"],20)]},
  {id:"easy-follow",en:"Easy follow",ar:"سهل المتابعة",blurbEn:"One cue at a time.",blurbAr:"إرشاد واحد في كل مرة.",style:"kickboxing",mode:"shadow",level:"beginner",rounds:3,roundSec:120,restSec:45,combos:[C("c1",["jab"],5),C("c2",["cross"],5),C("c3",["jab","cross"],6),C("c4",["jab","rear-mid-kick"],8)]}
];
RB.REVIEWS = [
  {quoteEn:"Excellent content — you actually learn.",quoteAr:"محتوى ممتاز — تتعلم فعلاً.",name:"Noura Al Mazrouei"},
  {quoteEn:"Every session feels like a real gym.",quoteAr:"كل حصة كأنها صالة حقيقية.",name:"Yusuf Rahman"},
  {quoteEn:"Great combos and enough variety.",quoteAr:"كومبو ممتاز وتنوع يكفي كي لا تمل.",name:"Lina Haddad"}
];
