window.RB = window.RB || {};
RB.FIGHTS_UPDATED = "2026-09-08";
RB.FIGHTER_PHOTOS = {
  "islam makhachev": "islam.jpg", makhachev: "islam.jpg",
  "alexander volkanovski": "volk.jpg", volkanovski: "volk.jpg",
  "ilia topuria": "topuria.jpg", topuria: "topuria.jpg",
  "alex pereira": "pereira.jpg", pereira: "pereira.jpg",
  "joshua van": "van.jpg",
  "alexandre pantoja": "pantoja.jpg", pantoja: "pantoja.jpg",
  "movsar evloev": "evloev.jpg", evloev: "evloev.jpg",
  "khabib nurmagomedov": "khabib.jpg", nurmagomedov: "khabib.jpg",
  "conor mcgregor": "mcgregor.jpg", mcgregor: "mcgregor.jpg",
  "israel adesanya": "adesanya.jpg", adesanya: "adesanya.jpg",
  "max holloway": "holloway.jpg", holloway: "holloway.jpg",
  "amanda nunes": "nunes.jpg", nunes: "nunes.jpg",
  "francis ngannou": "ngannou.jpg", ngannou: "ngannou.jpg",
  "dustin poirier": "poirier.jpg", poirier: "poirier.jpg",
  "jon jones": "jones.jpg",
  "valentina shevchenko": "shevchenko.jpg", shevchenko: "shevchenko.jpg",
  "zhang weili": "weili.jpg", weili: "weili.jpg",
  "natalia silva": "natalia.jpg",
  "jean silva": "jeansilva.jpg",
  "ryan garcia": "garcia.jpg",
  "conor benn": "benn.jpg",
  "canelo alvarez": "canelo.jpg", "saul alvarez": "canelo.jpg", canelo: "canelo.jpg", alvarez: "canelo.jpg",
  "isaac cruz": "cruz.jpg",
  "christian mbilli": "mbilli.jpg", mbilli: "mbilli.jpg",
  "merab dvalishvili": "merab.jpg", dvalishvili: "merab.jpg",
  "tom aspinall": "aspinall.jpg", aspinall: "aspinall.jpg"
};
RB.fighterPhoto = function (name) {
  const raw = String(name || "").toLowerCase().replace(/[.“”"']/g, "").replace(/\./g, "").trim();
  if (!raw || raw === "tbd") return null;
  const map = RB.FIGHTER_PHOTOS;
  if (map[raw]) return map[raw];
  const parts = raw.split(/\s+/).filter(Boolean);
  for (let i = Math.min(3, parts.length); i >= 1; i--) {
    const key = parts.slice(-i).join(" ");
    if (key.length > 3 && map[key]) return map[key];
  }
  for (const k of Object.keys(map)) {
    if (k.length > 5 && (raw.includes(k) || k.includes(raw))) return map[k];
  }
  return null;
};
RB.QUOTES = [
  { en: "Precision beats power, and timing beats speed.", ar: "الدقة تهزم القوة، والتوقيت يهزم السرعة.", name: "Conor McGregor", img: "mcgregor.jpg" },
  { en: "If you feel like a lion, you are a lion.", ar: "إن شعرت أنك أسد فأنت أسد.", name: "Khabib Nurmagomedov", img: "khabib.jpg" },
  { en: "I just do my job.", ar: "أنا أؤدي عملي فقط.", name: "Islam Makhachev", img: "islam.jpg" },
  { en: "I came here to be champion.", ar: "جئت لأكون بطلاً.", name: "Alex Pereira", img: "pereira.jpg" },
  { en: "Believing makes realities.", ar: "الإيمان يصنع الواقع.", name: "Ilia Topuria", img: "topuria2.jpg" },
  { en: "Blessed.", ar: "مبارك.", name: "Max Holloway", img: "holloway.jpg" },
  { en: "I'm not arrogant. I'm just better.", ar: "لست متكبراً. أنا أفضل فحسب.", name: "Israel Adesanya", img: "adesanya.jpg" },
  { en: "I didn't come this far to only come this far.", ar: "لم أصل إلى هنا لأتوقف هنا.", name: "Francis Ngannou", img: "ngannou.jpg" },
  { en: "I don't want to be the next Muhammad Ali. I want to be the first Jon Jones.", ar: "لا أريد أن أكون علي التالي. أريد أن أكون جون جونز الأول.", name: "Jon Jones", img: "jones.jpg" },
  { en: "I'm the best in the world.", ar: "أنا الأفضل في العالم.", name: "Amanda Nunes", img: "nunes.jpg" },
  { en: "I'm just a kid from Lafayette.", ar: "أنا مجرد فتى من لافاييت.", name: "Dustin Poirier", img: "poirier.jpg" },
  { en: "Victory is the most important thing.", ar: "النصر هو الأهم.", name: "Movsar Evloev", img: "evloev.jpg" }
];
RB.RANKINGS = [
  { rank: 1, en: "Islam Makhachev", ar: "إسلام ماخاشيف", img: "islam.jpg" },
  { rank: 2, en: "Alexander Volkanovski", ar: "ألكسندر فولكانوفسكي", img: "volk.jpg" },
  { rank: 5, en: "Ilia Topuria", ar: "إيليا توبوريا", img: "topuria.jpg" },
  { rank: 6, en: "Tom Aspinall", ar: "توم أسبينال", img: "aspinall.jpg" },
  { rank: 8, en: "Merab Dvalishvili", ar: "ميراب دفاليشفلي", img: "merab.jpg" },
  { rank: 9, en: "Alex Pereira", ar: "أليكس بيريرا", img: "pereira.jpg" },
  { rank: 11, en: "Joshua Van", ar: "جوشوا فان", img: "van.jpg" },
  { rank: 13, en: "Alexandre Pantoja", ar: "أليخاندري بانتوخا", img: "pantoja.jpg" }
];
RB.RANKINGS_W = [
  { rank: 1, en: "Valentina Shevchenko", ar: "فالنتينا شيفتشينكو", img: "shevchenko.jpg" },
  { rank: 3, en: "Zhang Weili", ar: "تشانغ ويلي", img: "weili.jpg" },
  { rank: 4, en: "Natalia Silva", ar: "ناتاليا سيلفا", img: "natalia.jpg" }
];
RB.SOURCES = [
  { id: "ufctime", en: "UFC Time schedule", ar: "جدول UFC Time", url: "https://ufctime.com/schedule" },
  { id: "espn-mma", en: "ESPN UFC scoreboard", ar: "لوحة ESPN للـ UFC", url: "https://site.api.espn.com/apis/site/v2/sports/mma/ufc/scoreboard" },
  { id: "espn-box", en: "ESPN boxing", ar: "ملاكمة ESPN", url: "https://www.espn.com/boxing/story/_/id/12508267/boxing-schedule" },
  { id: "boxlive", en: "Box.live", ar: "Box.live", url: "https://box.live/upcoming-fights-schedule/" },
  { id: "athlon", en: "Athlon UFC 2026", ar: "جدول Athlon للـ UFC", url: "https://athlonsports.com/mma/ufc-schedule-2026-dates-start-times-full-fight-cards" },
  { id: "ufc-rank", en: "UFC rankings", ar: "تصنيف UFC", url: "https://www.ufc.com/rankings" }
];
RB.FIGHTS = [
  { id:"noche-ufc-4", sport:"ufc", kind:"mma",
    en:"Noche UFC 4", ar:"نوتشي UFC 4",
    headlineEn:"Silva vs Delgado", headlineAr:"سيلفا ضد ديلغادو",
    a:{en:"Jean Silva",ar:"جان سيلفا",img:"jeansilva.jpg"}, b:{en:"Jose Miguel Delgado",ar:"خوسيه ميغيل ديلغادو",img:"f2.jpg"},
    date:"2026-09-12T21:00:00-04:00", venueEn:"Desert Diamond Arena, Glendale AZ", venueAr:"أريزونا — غلانديل",
    weightEn:"Featherweight", weightAr:"وزن الريشة", bouts:13, ppv:false, broadcast:"Paramount+",
    source:"https://ufctime.com/schedule", portrait:"f1.jpg", poster:"spar.jpg" },
  { id:"garcia-benn", sport:"boxing", kind:"boxing",
    en:"Zuffa Boxing", ar:"زوفا بوكسينغ",
    headlineEn:"Garcia vs Benn", headlineAr:"غارسيا ضد بن",
    a:{en:"Ryan Garcia",ar:"رايان غارسيا",img:"garcia.jpg"}, b:{en:"Conor Benn",ar:"كونور بن",img:"benn.jpg"},
    date:"2026-09-12T19:00:00-07:00", venueEn:"Las Vegas, Nevada", venueAr:"لاس فيغاس",
    weightEn:"WBC Welterweight title", weightAr:"لقب WBC وزن الوسط", bouts:9, ppv:true, broadcast:"Paramount+",
    source:"https://box.live/upcoming-fights-schedule/", portrait:"f3.jpg", poster:"poster.jpg" },
  { id:"ufc-331", sport:"ufc", kind:"mma",
    en:"UFC 331", ar:"UFC 331",
    headlineEn:"Van vs Pantoja 2", headlineAr:"فان ضد بانتوخا ٢",
    a:{en:"Joshua Van",ar:"جوشوا فان",img:"van.jpg"}, b:{en:"Alexandre Pantoja",ar:"أليخاندري بانتوخا",img:"pantoja.jpg"},
    date:"2026-09-19T22:00:00-07:00", venueEn:"Los Angeles, CA", venueAr:"لوس أنجلوس",
    weightEn:"Flyweight title rematch", weightAr:"إعادة لقب وزن الذبابة", bouts:13, ppv:true, broadcast:"PPV",
    source:"https://ufctime.com/schedule", portrait:"f2.jpg", poster:"spar.jpg" },
  { id:"cruz-bravo", sport:"boxing", kind:"boxing",
    en:"DAZN Boxing", ar:"ملاكمة DAZN",
    headlineEn:"Cruz vs Bravo", headlineAr:"كروز ضد برافو",
    a:{en:"Isaac Cruz",ar:"إسحاق كروز",img:"cruz.jpg"}, b:{en:"Nestor Bravo",ar:"نيستور برافو",img:"f2.jpg"},
    date:"2026-09-19T19:00:00-07:00", venueEn:"San Diego, CA", venueAr:"سان دييغو",
    weightEn:"WBC interim junior welter", weightAr:"لقب WBC مؤقت خفيف الوسط", bouts:6, ppv:false, broadcast:"DAZN",
    source:"https://www.espn.com/boxing/story/_/id/12508267/boxing-schedule", portrait:"f3.jpg", poster:"gloves.jpg" },
  { id:"ufc-fn-rosas", sport:"ufc", kind:"mma",
    en:"UFC Fight Night", ar:"ليلة قتال UFC",
    headlineEn:"Rosas Jr. vs Barcelos", headlineAr:"روساس ضد بارسيلوس",
    a:{en:"Raul Rosas Jr.",ar:"راؤول روساس"}, b:{en:"Raoni Barcelos",ar:"راوني بارسيلوس"},
    date:"2026-09-26T22:00:00-07:00", venueEn:"Las Vegas, NV", venueAr:"لاس فيغاس",
    weightEn:"Bantamweight", weightAr:"وزن البانتام", bouts:11, ppv:false, broadcast:"Paramount+",
    source:"https://ufctime.com/schedule", portrait:"f2.jpg", poster:"spar.jpg" },
  { id:"inoue-nasukawa", sport:"boxing", kind:"boxing",
    en:"Prime Video Boxing 16", ar:"برايم بوكسينغ ١٦",
    headlineEn:"Inoue vs Nasukawa", headlineAr:"إينوي ضد ناسوكاوا",
    a:{en:"Takuma Inoue",ar:"تاكوما إينوي"}, b:{en:"Tenshin Nasukawa",ar:"تنشين ناسوكاوا"},
    date:"2026-09-27T14:00:00+09:00", venueEn:"Toyota Arena Tokyo", venueAr:"طوكيو",
    weightEn:"WBC Bantamweight title", weightAr:"لقب WBC وزن البانتام", bouts:8, ppv:false, broadcast:"Prime Video",
    source:"https://box.live/upcoming-fights-schedule/", portrait:"f3.jpg", poster:"poster.jpg" },
  { id:"ufc-332", sport:"ufc", kind:"mma",
    en:"UFC 332", ar:"UFC 332",
    headlineEn:"Silva vs Wang", headlineAr:"سيلفا ضد وانغ",
    a:{en:"Natalia Silva",ar:"ناتاليا سيلفا",img:"natalia.jpg"}, b:{en:"Wang Cong",ar:"وانغ كونغ",img:"f1.jpg"},
    date:"2026-10-03T22:00:00-06:00", venueEn:"Salt Lake City, UT", venueAr:"سولت ليك سيتي",
    weightEn:"Women's flyweight", weightAr:"وزن الذبابة للنساء", bouts:12, ppv:true, broadcast:"PPV",
    source:"https://ufctime.com/schedule", portrait:"f1.jpg", poster:"spar.jpg" },
  { id:"whittaker-wallace", sport:"boxing", kind:"boxing",
    en:"DAZN Birmingham", ar:"برمنغهام",
    headlineEn:"Whittaker vs Wallace", headlineAr:"ويتكر ضد والاس",
    a:{en:"Ben Whittaker",ar:"بن ويتكر"}, b:{en:"Conor Wallace",ar:"كونور والاس"},
    date:"2026-10-03T19:00:00+01:00", venueEn:"Utilita Arena, Birmingham", venueAr:"برمنغهام، إنجلترا",
    weightEn:"Light heavyweight", weightAr:"وزن خفيف الثقيل", bouts:7, ppv:false, broadcast:"DAZN",
    source:"https://box.live/upcoming-fights-schedule/", portrait:"f3.jpg", poster:"gloves.jpg" },
  { id:"ufc-fn-allen", sport:"ufc", kind:"mma",
    en:"UFC Fight Night", ar:"ليلة قتال UFC",
    headlineEn:"Allen vs Duncan", headlineAr:"ألين ضد دنكان",
    a:{en:"Brendan Allen",ar:"بريندان ألين"}, b:{en:"Christian Leroy Duncan",ar:"كريستيان ليروي دنكان"},
    date:"2026-10-10T22:00:00-07:00", venueEn:"Las Vegas, NV", venueAr:"لاس فيغاس",
    weightEn:"Middleweight", weightAr:"وزن المتوسط", bouts:11, ppv:false, broadcast:"Paramount+",
    source:"https://ufctime.com/schedule", portrait:"f2.jpg", poster:"spar.jpg" },
  { id:"ufc-edmonton", sport:"ufc", kind:"mma",
    en:"UFC Edmonton", ar:"UFC إدمونتون",
    headlineEn:"Buckley vs Malott", headlineAr:"باكلي ضد مالوت",
    a:{en:"Joaquin Buckley",ar:"خواكين باكلي"}, b:{en:"Mike Malott",ar:"مايك مالوت"},
    date:"2026-10-17T19:00:00-06:00", venueEn:"Edmonton, Alberta", venueAr:"إدمونتون، كندا",
    weightEn:"Welterweight", weightAr:"وزن الوسط", bouts:12, ppv:false, broadcast:"Paramount+",
    source:"https://ufctime.com/schedule", portrait:"f2.jpg", poster:"spar.jpg" },
  { id:"dubois-wardley", sport:"boxing", kind:"boxing",
    en:"Heavyweight rematch", ar:"إعادة الوزن الثقيل",
    headlineEn:"Dubois vs Wardley II", headlineAr:"دوبوا ضد واردلي ٢",
    a:{en:"Daniel Dubois",ar:"دانيال دوبوا"}, b:{en:"Fabio Wardley",ar:"فابيو واردلي"},
    date:"2026-10-17T21:00:00+01:00", venueEn:"The O2, London", venueAr:"لندن — O2",
    weightEn:"Heavyweight", weightAr:"وزن الثقيل", bouts:6, ppv:true, broadcast:"DAZN",
    source:"https://box.live/upcoming-fights-schedule/", portrait:"f3.jpg", poster:"poster.jpg" },
  { id:"ufc-333", sport:"ufc", kind:"mma",
    en:"UFC 333", ar:"UFC 333",
    headlineEn:"Volkanovski vs Evloev", headlineAr:"فولكانوفسكي ضد إيفلويف",
    a:{en:"Alexander Volkanovski",ar:"ألكسندر فولكانوفسكي",img:"volk.jpg"}, b:{en:"Movsar Evloev",ar:"موفسار إيفلويف",img:"evloev.jpg"},
    date:"2026-10-24T18:00:00+04:00", venueEn:"Abu Dhabi, UAE", venueAr:"أبوظبي، الإمارات",
    weightEn:"Featherweight title", weightAr:"لقب وزن الريشة", bouts:9, ppv:true, broadcast:"PPV",
    source:"https://ufctime.com/schedule", portrait:"f2.jpg", poster:"spar.jpg" },
  { id:"canelo-mbilli", sport:"boxing", kind:"boxing",
    en:"Riyadh Season", ar:"موسم الرياض",
    headlineEn:"Canelo vs Mbilli", headlineAr:"كانيلو ضد إمبيلي",
    a:{en:"Canelo Alvarez",ar:"كانيلو ألفاريز",img:"canelo.jpg"}, b:{en:"Christian Mbilli",ar:"كريستيان إمبيلي",img:"mbilli.jpg"},
    date:"2026-10-31T21:00:00+03:00", venueEn:"ANB Arena, Riyadh", venueAr:"الرياض",
    weightEn:"WBC Super middleweight", weightAr:"لقب WBC وزن المتوسط الثقيل", bouts:8, ppv:true, broadcast:"DAZN PPV",
    source:"https://box.live/upcoming-fights-schedule/", portrait:"f3.jpg", poster:"poster.jpg" },
  { id:"ufc-fn-bonfim", sport:"ufc", kind:"mma",
    en:"UFC Fight Night", ar:"ليلة قتال UFC",
    headlineEn:"Bonfim vs Brady", headlineAr:"بونفيم ضد برادي",
    a:{en:"Gabriel Bonfim",ar:"غابرييل بونفيم"}, b:{en:"Sean Brady",ar:"شون برادي"},
    date:"2026-11-07T22:00:00-08:00", venueEn:"Las Vegas, NV", venueAr:"لاس فيغاس",
    weightEn:"Welterweight", weightAr:"وزن الوسط", bouts:8, ppv:false, broadcast:"Paramount+",
    source:"https://ufctime.com/schedule", portrait:"f2.jpg", poster:"spar.jpg" },
  { id:"ufc-335", sport:"ufc", kind:"mma",
    en:"UFC 335", ar:"UFC 335",
    headlineEn:"Las Vegas PPV", headlineAr:"لاس فيغاس PPV",
    a:{en:"TBD",ar:"يُعلن لاحقاً"}, b:{en:"TBD",ar:"يُعلن لاحقاً"},
    date:"2026-12-12T22:00:00-08:00", venueEn:"Las Vegas, NV", venueAr:"لاس فيغاس",
    weightEn:"Main event TBA", weightAr:"النزال الرئيسي لاحقاً", bouts:0, ppv:true, broadcast:"PPV",
    source:"https://ufctime.com/schedule", portrait:"f2.jpg", poster:"spar.jpg" }
];
